# How to migrate to v49 from v48

Please see [the release note](https://github.com/option-t/option-t/releases/tag/v49.0.0).

---

## Breaking Changes

### Summary

#### Path Changes

|               affected path                                       | Changes |
|------------------------------------------------------|---------|
| `option-t/plain_result/unwrap_or_throw_error`        | Moved   |
| `option-t/plain_result/unwrap_or_throw_unknown`      | Moved   |
| `option-t/plain_result/experimental/try_catch`       | Removed |
| `option-t/plain_result/experimental/try_catch_async` | Removed |

#### API changes

| affected path                                                     | affected items                             | Changes          |
|-------------------------------------------------------------------|--------------------------------------------|------------------|
| `option-t/plain_result`,  `option-t/plain_result/try_catch`       | `tryCatchIntoResultWithEnsureError`        | Behavior Changed |
| `option-t/plain_result`,  `option-t/plain_result/try_catch_async` | `tryCatchIntoResultWithEnsureErrorAsync`   | Behavior Changed |
| `option-t/plain_result/namespace`                                 | `Result.unwrapOrThrowWithEnsureError`      | Behavior Changed |
| `option-t/plain_result/namespace`                                 | `Result.unwrapOrThrowWithEnsureErrorAsync` | Behavior Changed |


### Details

#### Move `option-t/plain_result/unwrap_or_throw_error` & `option-t/plain_result/unwrap_or_throw_unknown` to `option-t/plain_result/deprecated/`. [#2313][#2313]

They were deprecated paths.
Please rewrite their import path or migrate to use `option-t/plain_result/unwrap_or_throw`.


#### Remove deprecated items from `option-t/plain_result` and `option-t/plain_result/namespace`. [#2310][#2310]

These items are removed.

- `option-t/plain_result`
    - `unwrapOrThrowWithEnsureErrorForResult()`: Replace with `unwrapOrThrowWithAssertErrorForResult()`
       from `option-t/plain_result/deprecated/unwrap_or_throw_error` instead.
- `option-t/plain_result/namespace`
    - `Result.unwrapOrThrowWithEnsureError()`: Replace with `unwrapOrThrowWithAssertErrorForResult()`
       from `option-t/plain_result/deprecated/unwrap_or_throw_error` instead.


#### `tryCatchIntoResultWithEnsureError()` does not throw `TypeError` if the passed producer function throws non `Error` instance of the current realm. [#2307][#2307], [#2311][#2311], and [#2317][#2317]

**This is behavior change.** 

Previously, their operators throw an error if throw `TypeError`
if the passed producer function throws a value that is not an `Error` instance of current [realm][realm].
Even if the thrown value is `Error` instance of cross-realm (e.g. `node:vm` or iframe),
their operators throws as "not an `Error` object".  It was tricky and strange behavior.

Now, we wrap it with a new `Error` instance of _current realm_  with setting a value
that is not an `Error` instance of current realm to `.cause` property of that new `Error` instance.
For almost use case, we think this is not a problematic. But this might change a error telemetry
or its stack trace in your observability tools. If would like to use a previous behavior, please use followings:

- `tryCatchIntoResultWithAssertError()` from `option-t/plain_result/deprecated/try_catch_with_assert_error`
- `tryCatchIntoResultWithAssertErrorAsync()` from `option-t/plain_result/deprecated/try_catch_with_assert_error_async`

Please see [#2286][#2286] to know why we do this change.


### Experimental Features

#### End of `option-t/plain_result/experimental/try_catch` & `option-t/plain_result/experimental/try_catch_async`. [#2312][#2312]

They become new implementations for `tryCatchIntoResultWithEnsureError`
from `option-t/plain_result/try_catch` (`option-t/plain_result/try_catch_async`) now. Please use them.

## Notable Deprecations during the previous major version

### Deprecated `unwrapOrThrowWithEnsureErrorForResult()` & `unwrapOrThrowUnknownDirectlyForResult` ([v48.1.0][v48.1.0])

- `unwrapOrThrowWithEnsureErrorForResult()` exported from
    - `option-t/plain_result`.
    - `option-t/plain_result/unwrap_or_throw_error`.
    - `option-t/plain_result/namespace` as `unwrapOrThrowWithEnsureError()`.
- `unwrapOrThrowUnknownDirectlyForResult()` exported from
    - `option-t/plain_result/unwrap_or_throw_unknown`.

Their operator rethrow directly the `Error` contained in a passed result object.
However, by rethrowing, its stack trace information lacks the information about where throws it actually.
Instead, we recommend to use `unwrapOrThrowForResult`.


[v48.1.0]: https://github.com/option-t/option-t/releases/tag/v48.1.0
[realm]: https://262.ecma-international.org/14.0/#realm
[#2286]: https://github.com/option-t/option-t/pull/2286
[#2307]: https://github.com/option-t/option-t/pull/2307
[#2310]: https://github.com/option-t/option-t/pull/2310
[#2311]: https://github.com/option-t/option-t/pull/2311
[#2312]: https://github.com/option-t/option-t/pull/2312
[#2313]: https://github.com/option-t/option-t/pull/2313
[#2317]: https://github.com/option-t/option-t/pull/2317
